/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ehira' at '16/11/01 21:42' with Gradle 3.0
 *
 * @author ehira, @date 16/11/01 21:42
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
