/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ehira' at '16/11/07 20:39' with Gradle 3.0
 *
 * @author ehira, @date 16/11/07 20:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
